// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjainvlnaudevsuhotex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqYWludmxuYXVkZXZzdWhvdGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDIxMDMsImV4cCI6MjA2NDkxODEwM30.JB-Z8aFp-EyXCHXLkgnia1cyuaq2taDecLE4QhmJ_Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);